Add minification support
Inqnuam/esbuild-plugin-handlebars pull request #6
Opened 2024-05-27 19:22 UTC by LuisUrrutia

## Description
I've made changes to allow the output of Handlebars templates to be minified. This is useful for providers with HTML size limitations or other similar restrictions. The `html-minifier-terser` package is used for minification.

The changes introduce two new options:

- `minifyOutput`: Specifies whether the output should be minified.
- `minifyOptions`: Allows adding specific options for `html-minifier-terser`.

## Example

```js
const esbuild = require('esbuild');
const handlebarsPlugin = require('esbuild-handlebars-plugin');

esbuild.build({
  entryPoints: ['src/index.js'],
  bundle: true,
  outfile: 'dist/bundle.js',
  plugins: [
    handlebarsPlugin({
      minifyOutput: true,
      minifyOptions: {
        collapseWhitespace: true,
        removeComments: true,
      }
    })
  ]
});
```

2024-05-27 19:58 UTC, Inqnuam requested changes
Hello and thanks for your PR! 🙏
please see comments I left

2024-05-27 19:58 UTC, Inqnuam commented on src/index.ts
> +import { minify } from "html-minifier-terser";
I don't see this module in package.json, I think we should put it in peerDependencies and let people to install it when needed

In consequences, the minier module should be imported dynamically based on minify options, see next comment 

please add a little test of runtime check or both ESM and CJS contexts

2024-05-27 19:58 UTC, Inqnuam commented on src/index.ts
>      setup(build: PluginBuild) {
we can mark this setup function async, then make the import(minifer module) statement

2024-05-27 20:15 UTC, LuisUrrutia commented on src/index.ts
> +import { minify } from "html-minifier-terser";
Ok, I have added the `peerDependency` and I dynamically imported it. 

What do you mean with "add a little test of runtime check"? I noticed that you have a `test` folder, but it is not actually something like a unit test.

2024-05-31 17:33 UTC, Inqnuam approved these changes
Thank you for the changes
ill make some tests before a new release

2024-07-30 14:15 UTC, LuisUrrutia commented
Hi there, any news on this?

2024-07-30 16:31 UTC, Inqnuam commented
Hello @LuisUrrutia, sorry been busy with the work
What if I add a new option, kind of custom hook where you can customise the output by yourself using tools you want ?

2024-10-10 12:13 UTC, closed without merging